### ISSUE TITLE
IEEEmadC

### ISSUE THREAD

**Issue by SangramChavan** [bensalcie/IEEE-Classroom-App#3]
Hello, Thank you for submitting your app to IEEEmadC we were unable to find few files in your github repo, we kindly request you to go through a sample submission https://github.com/kryacose/AREd_Engg_Graphics

**Comment by bensalcie** [comment]
Hello, thanks alot for reminding.....but we did submit the files, the
source code is the ony one which was large and would not be uploaded on git

**Comment by bensalcie** [comment]
Good afternoon, following your recent update on the madc ambassadors group,
we had earlier on submitted some files, but we were messaged that, some
could not be found, our github account has been having some issues  ,since
you specified that we need to submit before tonight,i have prepared the
necessary files and shared on drive for ease of access here

https://drive.google.com/folderview?id=1td9ctrTUw4bbtyhMkW9_z6J5TXhBqH8P
